services:
  mongodb:
    image: mongo
    container_name: hexagonal-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  product-service:
    build: .
    container_name: product-service
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/productdb

volumes:
  mongo-data:
