name: Integration Tests

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.stats()'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar tests
        env:
          MONGO_URL: mongodb://localhost:27017/productdb
        run: npm test




# valida el caso de uso accediendo a la bbdd Mongo real o Mongo Memory, validación completa
